Proxy functionality
Wattpad/dns-server pull request #3
Opened 2016-09-26 18:50 UTC by eavuong23

Included:
- dockerfiles
- docker-compose
- proxy rewriting rules
- database
- database view (index.html)
- database interface via POST requests
- script to generate certs (originally part of proxy2)

Issues:
- HTTPS on OSX and Chrome 53 do not work for some websites
- sometimes there are hanging database connections? need to investigate more
- need to test performance

2016-09-28 16:57 UTC, denniskpw requested changes
Looks good so far, some minor comments.

2016-09-28 16:57 UTC, denniskpw commented on create_certificate.sh
> +mkdir certs/
Add comment to why we need this directory.

2016-09-28 16:57 UTC, denniskpw commented on proxy/models.py
> +    modified_date = models.DateTimeField(auto_now=True)
👍

2016-09-28 16:57 UTC, denniskpw commented on proxy/views.py
> +@api_view(['GET', 'POST'])
Remove `POST`

2016-09-28 16:57 UTC, denniskpw commented on proxy/proxy2.py
> +                lowercase = header.lower().replace('-', '_')
Rename `lowercase` to something more meaningful

2016-09-28 16:57 UTC, denniskpw commented on proxy/urls.py
> +    url(r'^delete_id/?$', views.delete_id, name='delete_id'),
In the future, we'd like the endpoints to be more RESTful:
```python
url(r'^$', views.index, name='index'),  # HTML
url(r'^resources$'),  # GET, POST
url(r'^resource/<id>'),  # single resource operation GET, PUT, DELETE
```

2016-09-28 16:57 UTC, denniskpw commented on proxy/proxy2.py
> +                lowercase = header.lower().replace('-', '_')
I don't think we need to replace `-` with `_` here.

2016-09-28 16:57 UTC, denniskpw commented on proxy/proxy2.py
> +                break
If we break out some of this loop into another method, it would help increase readability and a comment or two will go a long way here.

2016-09-28 17:18 UTC, denniskpw commented on proxy/views.py
> +            return HttpResponse(status=204)
Should this be 201?

2016-09-28 17:31 UTC, eavuong23 commented on proxy/views.py
> +            return HttpResponse(status=204)
👍

2016-09-28 18:32 UTC, rays commented on proxy/urls.py
> +    url(r'^delete_id/?$', views.delete_id, name='delete_id'),
there is a django rest module

2016-09-28 18:34 UTC, rays commented on proxy/proxy2.py
> +                lowercase = header.lower().replace('-', '_')
why are we doing this?

2016-10-18 19:45 UTC, eavuong23 commented on proxy/proxy2.py
> +                lowercase = header.lower().replace('-', '_')
To clarify what `lowercase` actually should represent

2016-10-18 19:48 UTC, eavuong23 commented on proxy/proxy2.py
> +                lowercase = header.lower().replace('-', '_')
It is stored as `_` in our database though

2016-10-24 21:48 UTC, denniskpw approved these changes

2016-10-24 21:49 UTC, denniskpw commented
🚢

2016-10-26 19:07 UTC, merged